"""empty message

Revision ID: cc43cc1d9a32
Revises: fadac24661c6
Create Date: 2023-10-24 01:24:24.668264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc43cc1d9a32'
down_revision = 'fadac24661c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_set', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ussd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('previous', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ussd', schema=None) as batch_op:
        batch_op.drop_column('previous')
        batch_op.drop_column('stage')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_set')

    # ### end Alembic commands ###
